<?php
$data = [
    "data" => [
        "0" => [
            "DT_RowIndex" => 1,
            "name" => "Home",
            "robot" => "noindex, nofollow",
            "description" => "This is meta description for home",
            "keyword" => "Sample keyword 1, Sample keyword 2, Sample keyword 3",
            "action" => "01-0001",
        ],
        "1" => [
            "DT_RowIndex" => 2,
            "name" => "Product",
            "robot" => "noindex",
            "description" => "This is meta description for product",
            "keyword" => "Sample keyword 1, Sample keyword 2, Sample keyword 3",
            "action" => "01-0001",
        ],
        "2" => [
            "DT_RowIndex" => 3,
            "name" => "Blog",
            "robot" => "noindex",
            "description" => "This is meta description for blog",
            "keyword" => "Sample keyword 1, Sample keyword 2, Sample keyword 3",
            "action" => "01-0001",
        ],
        "3" => [
            "DT_RowIndex" => 4,
            "name" => "Contact",
            "robot" => "noindex",
            "description" => "This is meta description for product",
            "keyword" => "Sample keyword 1, Sample keyword 2, Sample keyword 3",
            "action" => "01-0001",
        ],
        "4" => [
            "DT_RowIndex" => 5,
            "name" => "Address",
            "robot" => "noindex, nofollow",
            "description" => "This is meta description for address",
            "keyword" => "Sample keyword 1, Sample keyword 3",
            "action" => "01-0001",
        ],
        "5" => [
            "DT_RowIndex" => 6,
            "name" => "About Us",
            "robot" => "nofollow",
            "description" => "This is meta description for about us",
            "keyword" => "Sample keyword 1, Sample keyword 2, Sample keyword 3, Sample Keyword 4",
            "action" => "01-0001",
        ],
        "6" => [
            "DT_RowIndex" => 7,
            "name" => "Partner",
            "robot" => "noindex",
            "description" => "This is meta description for partner",
            "keyword" => "Sample keyword 1, Sample keyword 3, Sample keyword 4",
            "action" => "01-0001",
        ],
        "7" => [
            "DT_RowIndex" => 8,
            "name" => "Vision & Mission",
            "robot" => "nofollow",
            "description" => "This is meta description for vision and mission",
            "keyword" => "Sample keyword 1, Sample keyword 2, Sample keyword 3, Sample Keyword 4",
            "action" => "01-0001",
        ],
        "8" => [
            "DT_RowIndex" => 9,
            "name" => "Profile",
            "robot" => "nofollow",
            "description" => "This is meta description for profile",
            "keyword" => "Sample keyword 2, Sample keyword 3, Sample keyword 4",
            "action" => "01-0001",
        ],
        "9" => [
            "DT_RowIndex" => 10,
            "name" => "Promotion",
            "robot" => "noindex, nofollow",
            "description" => "This is meta description for promotion",
            "keyword" => "Sample keyword 1, Sample keyword 2, Sample keyword 3, Sample keyword 4",
            "action" => "01-0001",
        ],
        "10" => [
            "DT_RowIndex" => 11,
            "name" => "Registration",
            "robot" => "nofollow",
            "description" => "This is meta description for registration",
            "keyword" => "Sample keyword 1",
            "action" => "01-0001",
        ],

    ],
    "draw" => 1,
    "recordsFiltered" => 2,
    "recordsTotal" => 2,
];
header('Content-Type: application/json; charset=utf-8');
echo json_encode($data);
